service: message-array

provider:
  name: aws
  runtime: nodejs10.x

functions:
  consume-queue:
    handler: handler.consumeQueue
    events:
      - sqs:
        arn: arn:aws:sqs:region:XXXXXX:myQueue
        batchSize: 1

plugins:
  - serverless-offline